# Generated by Django 3.0 on 2019-12-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20191207_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_teach',
            field=models.BooleanField(default=False),
        ),
    ]
