# Generated by Django 3.0 on 2019-12-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_user_is_teach'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='is_teach',
            field=models.BooleanField(default=False),
        ),
    ]
