# Generated by Django 3.0 on 2019-12-19 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_curso_is_teach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='is_teach',
        ),
    ]
